### ISSUE TITLE
我的JS重学之路

### ISSUE THREAD

**Issue by sunshineroper** [sunshineroper/sunshineroper.github.io#2]
因为在工作中越来越觉得自己的基础太薄弱,没有沉下心去学习技术..所以在这里记录开始我自己的JS重学之路 ,对于重学对我意义是重新开始学
![qq20170926-0](https://user-images.githubusercontent.com/18000311/30841880-115909f8-a244-11e7-866c-ed8680096e56.png)

更新中.......
必看的文章:
http://www.jianshu.com/p/cd3fee40ef59 前段进阶系列 *****
http://www.cnblogs.com/wangfupeng1988/p/4001284.html 深入理解javascript原型和闭包系列 *****
https://github.com/wangfupeng1988/js-async-tutorial 深入理解异步 *****
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Inheritance_and_the_prototype_chain 
基于原型链的继承 *****
https://juejin.im/post/59aa71d56fb9a0248d24fae3 从这两套题，重新认识JS的this、作用域、闭包、对象 *****
必看的书:
Javascript 犀牛书 *****
JavaScript高级编程 *****

楼下的所有内容都是我整理自文章或者书籍....没办法每一块都注明来自那个文章！海涵

**Comment by sunshinroper** [comment]
二楼记录学习进度

**Comment by sunshinroper** [comment]
### 函数和对象的关系
```javascript
/*
对象都是通过函数去创建的
*/
console.log(typeof (Object));  // function
console.log(typeof (Array));  // function
```

**Comment by sunshinroper** [comment]
### 一切皆是对象
```javascript
/*
	在javascript中可以用typeof操作符去输出类型
	undefined, number, string, boolean 四种类型都是简单的值类型 
	剩下的函数 数组 对象都是引用类型
	关于null:  用typeof 操作符去输出类型的话会输出Object
	在<javascript权威指南中>说到可以把null理解为一个特殊的对象,含义是非对象
	关于为什么用typeof 运算符会输出Object,看过一位朋友的评论是这样的说道 在js中，因为底层是用二进制编码的，所以如果前三位是000的话,用 typeof 的话就会返回object,而null的编码是全部都是0，所以也会被返回object ,所以这其实是js的一个bug而已。
*/
console.log(typeof 'abc'); // string
console.log(typeof true);  // boolean
console.log(typeof null);  //object
function fn () {}
console.log(fn instanceof Object) // 通过instanceof可以判断一个变量是否是对象
```

**Comment by sunshinroper** [comment]
### prototype原型
函数也是一种对象,在Javascript中给每个函数默认定义了一个属性prototype,默认只有一个constructor的属性,prototype的属性值是一个对象
```javascript
// 也可以在自定义的prototype中自定义属性
// 每个对象都有一个隐藏的属性, __proto__ 个属性引用了创建这个对象的函数的prototype
function Fn() { }
	Fn.prototype.name = 'demo';
	Fn.prototype.getYear = function () {
	return 123;
};
// 为什么Fn.name 会输出 demo 不是应该是 Fn.prototype.name才行嘛
/*
	这里会设计到一个在原型链上查找的问题,在Javascript权威指南中这样说到: 会先在对象上查找，如果存在则使用对象的属性，如果对象上不存在，则到本对象原型链上查找，如果找到则使用原型上的属性，如果没有继续到上一层查找，以此类推，直到Object的原型。
本例中，因为fn没有name属性，所以会去原型链查找。
*/

````

**Comment by sunshinroper** [comment]
### 隐式原型 __proto__
没撸出来....后期填坑 先附一段教程
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Inheritance_and_the_prototype_chain

**Comment by sunshinroper** [comment]
### instanceof
![enter description here][1]

  Instanceof的判断队则是：沿着A的__proto__这条线来找，同时沿着B的prototype这条线来找，如果两条线能找到同一个引用，即同一个对象，那么就返回true。如果找到终点还未重合，则返回false。
  ```javascript
  console.log(Function instanceof Object) // true
  console.log(Object instanceof Function) // true
  ```


  ![enter description here][2]


  [1]: ./images/E8CBF1AA-9021-4E34-B46B-FEDC91388472_1.png "E8CBF1AA-9021-4E34-B46B-FEDC91388472"
  [2]: http://images.cnitblog.com/blog/138012/201409/181637013624694.png

**Comment by sunshinroper** [comment]
### 继承

```
function fn () {
}
var fn1 = new Fn()
fn1.name = 'sunshine'

fn1.prototype.name = 'monshine'
console.log(fn1.name) /// snshine
// fn1 是fn函数new出来的对象 fn1.__proto__ =fn.prototype

```
![enter description here][1]


  [1]: http://images.cnitblog.com/blog/138012/201409/182013450814552.png

**Comment by sunshinroper** [comment]
### 执行上下文
变量、函数表达式——变量声明，默认赋值为undefined；
this——赋值；
函数声明——赋值；
```javascript
/*
	函数在创建的时候就确定了自由变量的作用域
*/
var a = 10 
function fn () {
	console.log(a) // 自由变量 函数创建的时候就确定了 a的作用域
}
function fn2(f) {
	var a = 20
	f() // 10
}
```
全局代码上下文环境
普通变量（包括函数表达式），

如： var a = 10;

声明（默认赋值为undefined）

函数声明，

如： function fn() { }

赋值

this

赋值

函数体
参数

赋值

arguments

赋值

自由变量的取值作用域

赋值

**Comment by sunshinroper** [comment]
### 作用域和上下文环境
作用域在函数创建的时候就已经确定了
```javascript
var a = 10
var b = 20  //全局作用域
function fn (x) {
	var a = 100
	      c = 200 // fn作用域
	 function bar(x) {
	 var a = 400
	 var d = 123 // bar作用域
	 } 
	 bar (100)
	 bar(200)
}
fn(10)
```
全局上下文环境
a = 10 b = 20
fn(10) 调用执行环境压栈进入活动状态
x=10 a=100 c=100
执行到bar(100) 调用执行环境压栈进入活动状态
x = 100 a = 400 d = 123
代码执行到bar(200) bar(100)执行环境销毁 bar(20)调用执行环境压栈进入活动状态
x=200 a=400 d=123
执行完bar(200)调用结束 bar(200)执行环境销毁 fn(10)重新进入活动状态
fn(10)执行完 销毁 全局上下文进入活动状态

作用域中变量的值是在执行过程中产生的确定的，而作用域却是在函数创建时就确定了。

所以，如果要查找一个作用域下某个变量的值，就需要找到这个作用域对应的执行上下文环境，再在其中寻找变量的值。

**Comment by sunshinroper** [comment]
### 自由变量 作用域链
自由变量: 在A中使用变量x但是在A中没有定义,对A来说就是自由变量
```javascript
	var a = 10
	function fn () {
		console.log(a)
	}
	// a就是自由变量从,从创建这个函数的作用域中取值
```
第一步，现在当前作用域查找a，如果有则获取并结束。如果没有则继续；

第二步，如果当前作用域是全局作用域，则证明a未定义，结束；否则继续；

第三步，（不是全局作用域，那就是函数作用域）将创建该函数的作用域作为当前作用域；

第四步，跳转到第一步。
